version: 2
jobs:
  build & stage:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run: echo "Checked out, ready to install dependencies."
      - run: npm install
      - run: mkdir -p my_workspace
      - run: apk add ca-certificates
      - run: echo "Dependencies installed successfully." > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt-get update
      - run: apt -y install nodejs
      - run: apt -y install build-essential
      - run: apt -y install npm
      - run: npm install -g testengine-cli
      - run: testengine --version
      - run: testengine -u circleci -p circlecitest jobs report output=./reports format=junit da4395ff-6238-4f0f-91ef-ab8c52788281
      - store_artifacts:
          path: ./reports
      - run: ls ./reports
      - store_test_results: 
          path: ./reports/output.xml
  deploy:
    docker:
      - image: node:8-alpine
    steps:
      - run: echo "hello!"
workflows:
  version: 2
  main_process:
    jobs:
      - build & stage
      - test:
          requires:
            - build & stage
      - deploy:
          requires:
            - test