---
swagger: "2.0"
info:
  description: A simple calculator for internal consumption
  version: 2.0.0
  title: Smartbear Calculator
  contact:
    email: math.whiz@smartbear.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /nathansAPIs/smart-calculator/2.0.0
schemes:
- https
- http
paths:
  /status:
    get:
      summary: Smoke call
      description: Validate the API is alive
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
                example: Running
  /add:
    post:
      summary: Add two numbers together.
      operationId: addInput
      produces:
      - application/json
      parameters:
      - name: inputOne
        in: query
        description: First input to resolve
        required: true
        type: string
      - name: inputTwo
        in: query
        description: First input to resolve
        required: true
        type: string
      responses:
        "200":
          description: Successful operation.
          schema:
            $ref: '#/definitions/resultAdd'
        "404":
          description: Bad input.
          schema:
            $ref: '#/definitions/error'
  /subtract:
    post:
      summary: Subtract inputOne from inputTwo.
      operationId: subtractInput
      produces:
      - application/json
      parameters:
      - name: inputOne
        in: query
        description: First input to resolve
        required: true
        type: string
      - name: inputTwo
        in: query
        description: First input to resolve
        required: true
        type: string
      responses:
        "200":
          description: Successful operation.
          schema:
            $ref: '#/definitions/resultSubtract'
        "404":
          description: Bad input.
          schema:
            $ref: '#/definitions/error'
  /multiply:
    post:
      summary: multiply inputOne and inputTwo
      operationId: multiplyInput
      produces:
      - application/json
      parameters:
      - name: inputOne
        in: query
        description: First input to resolve
        required: true
        type: string
      - name: inputTwo
        in: query
        description: First input to resolve
        required: true
        type: string
      responses:
        "200":
          description: Successful operation.
          schema:
            $ref: '#/definitions/resultMultiply'
        "404":
          description: Bad input.
          schema:
            $ref: '#/definitions/error'
  /divide:
    post:
      summary: Divdie inputOne into inputTwo
      operationId: divideInput
      produces:
      - application/json
      parameters:
      - name: inputOne
        in: query
        description: First input to resolve
        required: true
        type: string
      - name: inputTwo
        in: query
        description: First input to resolve
        required: true
        type: string
      responses:
        "200":
          description: Successful operation.
          schema:
            $ref: '#/definitions/resultDivide'
        "404":
          description: Bad input.
          schema:
            $ref: '#/definitions/error'
definitions:
  resultAdd:
    type: object
    required:
    - result
    properties:
      result:
        type: integer
        format: int64
        example: 4
  resultSubtract:
    type: object
    required:
    - result
    properties:
      result:
        type: integer
        format: int64
        example: 0
  resultMultiply:
    type: object
    required:
    - result
    properties:
      result:
        type: integer
        format: int64
        example: 16
  resultDivide:
    type: object
    required:
    - result
    properties:
      result:
        type: integer
        format: int64
        example: 1
  error:
    type: object
    required:
    - message
    properties:
      message:
        type: string
        example: Error in request
x-aws-api-id: 0yujjrhfpi
